### ISSUE TITLE
Browsers still shows uninstalled apps/profiles, even after a refresh

### ISSUE THREAD

**Issue by jonnyborbs** [Browsers-software/browsers#138]
**Describe the bug**
I recently uninstalled Chrome from my system entirely. Browsers still detects and displays it after a refresh, and I'm not sure why. MacOS does prompt me with a "Allow Browsers to access data from other apps?" prompt which I always permit, but then Chrome is re-detected anyway.

I've hidden the profiles in the config for the meantime but am wondering why this is happening.

**System:**
 - OS: Sonoma 14.3
 - Browsers Version 0.5.1 (I know 0.5.2 is out but it's not yet showing up in Homebrew to install, if that version fixes this issue just let me know!)

**Comment by liias** [comment]
Could you make a copy of `~/Library/Caches/software.Browsers/installed_browsers.json` and then delete the original file.
What happens now when you run Browsers?

**Comment by jonnyborbs** [comment]
That fixed the issue with Chrome showing back up when it shouldn't, but now I have a new problem - Arc won't launch based on the rules defined in config.json. I tried removing the #Default from the profiles since you removed browser support in 0.5.2. This is a different problem, so I'll open a new issue.
