### ISSUE TITLE
Mullvad support

### ISSUE THREAD

**Issue by RAVENz46** [Browsers-software/browsers#140]
I want you to add Mullvad browsers and ungoogle-chromium's entry points.

**Comment by liias** [comment]
Hi. What kind of support you are lacking for those browsers?
Which operating system are you using?

**Comment by liias** [comment]
About Mullvad browser - if you use [this package](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/networking/browsers/mullvad-browser/default.nix#L139), then from the looks of it the `.desktop` file is missing:
`MimeType=x-scheme-handler/http;x-scheme-handler/https;`

**Comment by RAVENz46** [comment]
@liias 
Thanks for your advice!
Add mimetype to .desktop solve this issue!

**Comment by liias** [comment]
Thanks for fixing it in source! https://github.com/NixOS/nixpkgs/commit/d712b00d96e3ce637a59383c787c1bf18df53598
