### ISSUE TITLE
Easier access to rules editor

### ISSUE THREAD

**Issue by unikitty37** [Browsers-software/browsers#193]
**Is your feature request related to a problem? Please describe.**
In order to edit a rule, I have to click on a button in the corner of the Browsers pop-up, then choose Preferences from the menu — which means I must first find a link that _isn't_ covered by a rule in order to cause the popup to appear.

**Describe the solution you'd like**
I'd like Browsers to have an icon in the system tray on KDE so I can right-click on it and access the preferences directly from there.

**Describe alternatives you've considered**
I've tried launching Browsers manually, but no window opens — the icon appears in the task bar briefly, then vanishes. Having this bring the preferences window up would be an acceptable alternative (and possibly easier to implement in a cross-platform way :)

At the moment I have a link to https://example.com that I've sent to myself in Slack; that allows me to go to my notes and click the link (as long as I never set a rule for example.com, of course!) But this only works particularly well if I don't have a load of notes to myself in Slack, as otherwise I have to find it first.

**Additional context**
I'm not sure how it works on other OSes — on macOS, it would need to run as a menu bar app if it doesn't already.

**Comment by liias** [comment]
Hey there! Thanks for feedback!

On macOS, just launching Browsers on its own will ignore all rules, allowing to access Preferences.

You mention KDE - which Linux distro are you using?

One of my goals is to keep the app _not_ running in the background, so unfortunately the system tray is not going to have it.

**Comment by unikitty37** [comment]
I'm using Kubuntu 24.04. Launching Browsers on its own also works as on macOS here, so I'm not sure why it didn't when I tried it beforehand. Possibly some window rule had kept something on top of it — but it works in a way that allows me to get at the rules easily, so I'll close this. Thanks for your time!
