### ISSUE TITLE
Browsers does not detect Waterfox

### ISSUE THREAD

**Issue by unikitty37** [Browsers-software/browsers#199]
**Describe the bug**
When I have Waterfox installed at /usr/local/bin/waterfox, it does not appear in the browser menu.

**System:**
 - OS: Kubuntu 22.04
 - Browsers Version [e.g. 0.22.1] v0.5.6

**Comment by liias** [comment]
In linux-based desktop environments, all applications, that have a `.desktop` file with `MimeType` including `x-scheme-handler/https`, are included. Please verify if the desktop file has MimeType set. If possible let's get Waterfox packager to fix it then as well.

**Comment by unikitty37** [comment]
Thanks — the problem with Waterfox is it just gives you a tarball and leaves you to write your _own_ .desktop file — and I'd omitted that line.

Replacing my own .desktop file with the Firefox one (with name, path, and icon changed, obviously) fixed the issue and Waterfox now shows in the list.

Thanks for your help, and sorry for the noise.
