### ISSUE TITLE
Firefox is not visible in MX-Linux Xfce

### ISSUE THREAD

**Issue by liias** [Browsers-software/browsers#20]
Xfce-based Firefox is not reported for https mimetype.
Also the built-in browser is not reported (in .desktop file it uses some xfce specific mimetype field).

**Comment by GRbit** [comment]
I've added custom *.desktop files after I've installed `browsers`, and it didn't detected it even after I've hit refresh button.

BUT after reboot it finally found these files I've created. At the same time, it still didn't found the original files.

Here is the original file:
```
[0] $ cat userapp-Firefox-R6VET0.desktop
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
NoDisplay=true
Exec=/opt/firefox/firefox-bin %u
Name=Firefox
Comment=Custom definition for Firefox
```

Here is the file I've created that was successfully detected after reboot (but not after Refresh):
```
[0] $ cat firefox-work.desktop 
#!/usr/bin/env xdg-open

[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Categories=Web-Browser;Browser;
Name=Firefox Work
Comment=Working profile of Firefox browser
Exec=/opt/firefox/firefox-bin -P Work --class=firefox-work --new-tab %u
Icon=firefox
Terminal=false
StartupNotify=true
StartupWMClass=firefox-work
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
```

**Comment by liias** [comment]
Hey, @GRbit, thanks again for testing. I tried out in VM and think I have a solid fix:

First, download latest Browsers version, this will help the app to identify Firefox as Firefox (so it adds Firefox profile support).

1. Edit the original firefox desktop file
`sudo nano /usr/share/applications/firefox.desktop`
2. Add these two values to MimeType (they really should be there already but are not in MX Linux for some reason)
`MimeType=x-scheme-handler/https;x-scheme-handler/http;...`
3. Save the file and update the desktop file database
`sudo update-desktop-database`
4. Run Refresh in Browsers and reopen Browsers if required

So the root cause really is that those two scheme handlers are missing for some reason in MX Linux Firefox.
I could add some other mimetypes to detect, like html mimetype, but I'm a bit confused why MX Linux does not have them in firefox.desktop unlike all the other distros.

**Comment by GRbit** [comment]
@liias 
Wow! That's very cool that you've found time to work on it so fast!

I did exactly as you said, unfortunately, it doesn't help. "Browsers" didn't find just firefox, it detects only the two desktop files that I've created, even after `sudo update-desktop-database` and running refresh in "Browsers" and re opening it. Maybe reboot will change something, but I can't do it right now. Will post an update later.

I've downloaded the latest version from the website. Is it ok, or should I compile it from source?

**Comment by liias** [comment]
Hmm, not sure why it does not work.
Another think you can try is to rename/copy your own `firefox-work.desktop` to one of:
- `firefox.desktop`
- `firefox_firefox.desktop`
- `firefox-esr.desktop`

Then Browsers will know that it's a firefox browser, and adds support for profiles.

Also, keep only this for exec:
`Exec=/opt/firefox/firefox-bin %u`

Browsers Will take `/opt/firefox/firefox-bin %u`, remove ` %u` suffix, and hope for the best that rest is a program path that can be executed (if not absolute, then it searches from PATH).

**Comment by GRbit** [comment]
Sorry for taking so much time to test it, but here is my update.

After renaming the original file to `firefox.desktop` and adding mime types to it, "Browser" app didn't found it even after a reboot. I don't why, but it is how it is.

The main problem for me is that my profile doesn't work. Like they were located with browsers, but when I choose them nothing happens. At the same time LibreWolf works fine, Chromium works fine, everything else just works out of the box.

I'm quite confused with your suggestion to keep exec `Exec=/opt/firefox/firefox-bin %u`. How do I choose profile then? I need to add `-P Work` to the command. Though, it still ends with `%u` suffix, so it should work, but, unfortunately, it doesn't.

**Comment by liias** [comment]
Hey. Sorry, I realize, I never responded on this.

> The main problem for me is that my profile doesn't work. Like they were located with browsers, but when I choose them nothing happens. At the same time LibreWolf works fine, Chromium works fine, everything else just works out of the box.
> I'm quite confused with your suggestion to keep exec Exec=/opt/firefox/firefox-bin %u. How do I choose profile then? I need to add -P Work to the command. Though, it still ends with %u suffix, so it should work, but, unfortunately, it doesn't.

If Browsers identifies that you have firefox installed (by the `.desktop` file name), then it reads the firefox profiles file and automatically adds all profiles in Browsers and knows to use `-P <profile-name>` command line argument.
However, since last time I wrote this, browsers now also supports command line flags for `Exec=` line, so custom command line arguments should also work now (but in case Browsers detects profiles, you should still not add the -P flag, otherwise there will be two -P flags and it would be indeterminate what will happen).

**Comment by liias** [comment]
I will close this for now. Browsers will not detect desktop items which don't have https scheme handler, and I'm going to keep that, as it's a rare case and easy to fix per .desktop file when such browser exists.

I'm not sure about any other issues you had, but if there is still something up, feel free to re-open.
