### ISSUE TITLE
Follow redirects and match rules against the eventual destination

### ISSUE THREAD

**Issue by unikitty37** [Browsers-software/browsers#202]
**Is your feature request related to a problem? Please describe.**
My work emails come through Microsoft 365 which redirects links through its own scanner, making them look like this:

`https://nor01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-[…snipped]`

This isn't matched by a rule matching `https://github.com/notifications`, but links sent through Slack do not have the scanner wrapping them.

**Describe the solution you'd like**
It would be great if Browsers could follow redirects before applying rules, so that a rule could match the protected version as well as an unscanned version posted in Slack.

**Describe alternatives you've considered**
* Having every rule duplicated, with the duplicate having the scanner wrapper (and having to URL-encode the actual link myself), which is a lot of effort.
* Replacing the rules with regexp rules, which makes them unreadable in very short order.

**Additional context**
I'm used to Choosy and Velja on macOS, which both offer this option; it saves a lot of hassle.

**Comment by liias** [comment]
Hey, thanks for feature request, I've definitely considered supporting specific list of trackers. Not only for url rules, but also to actually open the target link directly. Probably won't do it any time soon, but it's definitely high in the list.
