### ISSUE TITLE
Open browser with a number hotkey

### ISSUE THREAD

**Issue by GRbit** [Browsers-software/browsers#21]
Even though I use mouse for clicked links, it's very convenient to use keyboard to choose the browser I want.

It would be great to display numbers before (or after) each browser in a list, and open the link in needed browser hitting this hotkey.

Example image
![image](https://user-images.githubusercontent.com/6090120/233960029-ce245c26-2b5a-4478-9c31-4a61435b70e2.png)

**Comment by liias** [comment]
Definitely a good idea, will add it to the backlog!

**Comment by liias** [comment]
This landed in version 0.3.7.
It doesn't allow specifying hotkey to specific browser, but always shows them from 1-9.
