### ISSUE TITLE
Support Container Tabs for Zen Browser (Firefox fork)

### ISSUE THREAD

**Issue by grizzogor** [Browsers-software/browsers#218]
**Is your feature request related to a problem? Please describe.**
I've started to switch over from Firefox to Zen Browser (https://zen-browser.app/), which is an alternative Firefox fork that's similar to Arc. I've used Container Tabs in Firefox to keep browsing data separate for personal, schoolwork, and work-related uses, which Browsers does support with the use of the "Open external links in a container" add-on. 
While Browsers does have basic support for Zen Browser, it does not have support for Container Tabs. Links opened in Zen Browser open in the default "No Container" tab type.

**Describe the solution you'd like**
Add support for Container Tabs (like Firefox has) for Zen Browser.

**Comment by liias** [comment]
Hi @grizzogor 


In Zen Browser go to `about:profiles` in the web url entry and look for "Root Directory".
Then copy the `<config_dir_relative>` part from `/Users/xyz/Library/Application Support/<config_dir_relative>/Profiles/...`


If macOS, you could go to Applications in Finder, right click on Browsers and choose Show Package Contents.
Then go to Contents->Resources->repository
In that directory edit `application-repository.toml` and add this section:

```toml
[[apps]]
id = "org.mozilla.com.zen.browser"
config_dir_relative = "Firefox"
kind = "FIREFOX"
os = "MAC"
```

**Comment by grizzogor** [comment]
Yep, that works great. The `config_dir_relative` in my case is `zen`.
Thanks!
