### ISSUE TITLE
Support for regex in rule url patterns 

### ISSUE THREAD

**Issue by Charlignon** [Browsers-software/browsers#224]
**Is your feature request related to a problem? Please describe.**
I like the fact that you can set default apps for links. It was the feature that made me choose Browsers over other apps.  However, the syntax can be a bit frustrating : since components are exact match, you need to manually include all versions of a domain/url. For example, Youtube can be `www.youtube.com`, `youtube.com`, `www.youtube.fr`, `m.youtube.com`...

**Describe the solution you'd like**
I'd like to be able to use proper regexes to set up default apps, in a similar fashion as [Redirector](https://github.com/einaregilsson/Redirector)

**Describe alternatives you've considered**
None

**Additional context**
Linux

**Comment by liias** [comment]
Hey @Charlignon

The matcher should be able to handle this usecase:
- `*.youtube.com` should match `subdomain.youtube.com`
- `**.youtube.com` should match `subdomain.youtube.com` and `subdomain.subdomain.youtube.com` etc
- `**.youtube.*` should match same as previous but with any top-level-domain, this is probably the one you'd want here

**Comment by Charlignon** [comment]
Oh nice ! Thank you for your answer, it does cover my usecase :)
Thanks for adding it to the wiki ! I'll mark this issue as resolved
