### ISSUE TITLE
Cannot launch qutebrowser

### ISSUE THREAD

**Issue by jonathanabennett** [Browsers-software/browsers#32]
**Describe the bug**
Qutebrowser does not launch.

**To Reproduce**
1. Open Browsers
2. Click on Qutebrowser in the list of options
3. Browsers closes and nothing happens

**Expected behavior**
I expected Qutebrowser to open

**Screenshots**
Not really applicable here because nothing opens.

**Desktop (please complete the following information):**
 - OS: ArcoLinux (i3)
 - Browser: Qutebrowser (all other browser launch
 - Version:  2.5.4 I don't know how to find out the Browsers version number, I just installed it 2 days ago.
 
**Additional context**
Qutebrowser launches just fine from the command line, from Rofi, and is located in the same folder as Vivaldi (which launches just fine from within Browsers), /usr/bin/.

**Comment by liias** [comment]
Hey there. I tested qutebrowser in debian and it seems to work alright.
Please check and report back what's in the `Exec` value of the qutebrowser .desktop file.

I might need to handle more complex commands better (Browsers doesn't accept a command actually and assumes there's only a binary path (or just a binary name inside PATH, except the suffix `%u`.)

**Comment by jonathanabennett** [comment]
There are 3, one under [Desktop Entry]
Exec=qutebrowser --untrusted-args %u

One under [Desktop Action new-window]
Exec=qutebrowser

One under [Desktop Action preferences]
Exec=qutebrowser "qute://settings"

I don't know which one is being executed by Browsers.

**Comment by liias** [comment]
This should be fixed now in 0.3.4, released today. You can see the version in `⋮`->`About`.

Let me know if that solved it for you.

**Comment by jonathanabennett** [comment]
Working on 0.3.4. Thank you!
