### ISSUE TITLE
Doesn't seem to open in private window in i3

### ISSUE THREAD

**Issue by goproslowyo** [Browsers-software/browsers#66]
First of all, thanks for putting together this tool, it is extremely useful and important part of my workflows (generally, choosing which application handles links)!

**Describe the bug**
The documentation says I should be able to open in a private/incognito windows: `To open a link in incognito/private mode hold down ⇧ Shift while clicking on the browser`. This doesn't seem to work in my desktop environment and instead launches to the correct browser profile but it doesn't open in a private/incognito window.

[private-window.webm](https://github.com/Browsers-software/browsers/assets/68455785/3fb1419b-97c9-46f1-bd08-5b0e55efb9a6)

Also, could it be possible to press `shift+browser number` to open in private window for that browsers?
I tried `shift+2` but only shift+clicking seemed to respond to launching the desired browser.

Sorry, one more thing -- this is a feature request and I can file it separately but I'd like to be able to press `ctrl+#` or hold `ctrl` to open in the chosen browser but in a new window for the profile. (I don't know much Rust but might try to figure out how to do this...) Thanks again for your work :)

**System:**
 - OS: Ubuntu 23.04 with i3-gaps
 - Browsers Version:
   - Firefox: 114.0.1 (64-bit)
   - Chromium: Version 114.0.5735.90

**Comment by liias** [comment]
Hello there goproslowyo!

I'm glad you also find this tool useful!

Thanks for reporting this issue. It's now fixed in 0.3.9.
This also includes using `shift`+`<number key>`.

About opening a new window when pressing ctrl: this is quite dependant on OS and the browser itself, so it would take some time to test all of them. Please report a separate feature request. In theory it fits my vision for the app, so I think this idea could be useful, however could you tell me your usecase though - why do you want to open links in a new window?

I'm closing this as fixed, feel free to still answer here.

**Comment by goproslowyo** [comment]
Hey @liias awesome, I'll checkout the latest code and compile and test in a few days and I'll also create an issue for the new windows one.

The use case, at least for me I use i3 so I don't use the mouse too much that often and it's convenient to quickly open a link in a new windows and put it on another screen or rearrange it using keyboard. When it opens in a new tab, I have to mouse over to the new tab it opened and pull it out of the existing window. That's basically the reason. To not use the mouse basically :)

**Comment by liias** [comment]
Got it, thx for explaining your usecase.

Now I'm also curious - do you always compile from source if source is available? (e.g for trust reasons). Just mentioning, because latest release is also released as binary already. Just asking in case visibility of that is low.

**Comment by jfpedroza** [comment]
I have the same issue but only with Firefox. Chromium works properly.

System:

    OS: EndeavourOS with i3
    Browsers Version:
        Firefox: 117.0.1
        Chromium: Version: 117.0.5938.62
