### ISSUE TITLE
Opening links in a Firefox container cuts of URL parameters

### ISSUE THREAD

**Issue by blandir** [Browsers-software/browsers#73]
**Describe the bug**
Opening the URL https://testpage.nodomain?test=1&test2=test in a Firefox tab works.
Opening this URL in a _container_ tab cuts off `&test2=test`, ie. only https://testpage.nodomain?test=1 is called.

**System:**
 - OS: MacOS Ventura 13.4.1
 - Browsers Version Firefox 115.0.2

**Comment by liias** [comment]
Thank you for the report. I can confirm it happens for me as well. Will look into it when I have some spare time.

**Comment by liias** [comment]
@blandir this should be fixed now in version 0.4.0.

**Comment by blandir** [comment]
I fully support being conservative with new dependencies. I'm also not a Rust developer, but I will give this a shot.

**Comment by liias** [comment]
This is now part of 0.4.1. Thanks again, @blandir!
