### ISSUE TITLE
Easier dismissal of popup

### ISSUE THREAD

**Issue by jonnyborbs** [Browsers-software/browsers#77]
**Is your feature request related to a problem? Please describe.**
It's a little annoying when you click a link, and the Browsers popup displays, but then you decide you didn't want to follow the link. It's normal enough to change your mind, but dismissing the popup requires several clicks; entering the kebab, navigating to "quit", and clicking it.

If you *don't* take these steps, and don't follow through with your link click, the window hangs around until the next URL interaction. It remains on top of other windows and loses context immediately if you change to a new application.

**Describe the solution you'd like**
If I click outside the Browsers popup, it should go away as any other context menu would.

**Describe alternatives you've considered**
Just continuing to use the multi-step workflow, but I don't love it 😄

**Comment by liias** [comment]
Hey, @jonnyborbs 

I can definitely see how closing on unfocusing can be convenient. It was actually my first attempt, but it didn't work well enough in all operating systems. I will consider adding it as an option to settings.

One hint how I close it right now: just activate the window by clicking on it, if it isn't activated already and then press Esc key on your keyboard.

**Comment by jonnyborbs** [comment]
Thanks! That does work, though finding an area of the popup that isn't a browser name or the kebab is also a bit of a hunting task (the URL string is the best bet) - appreciate the feedback, look forward to anything you can do to address though 😄

**Comment by liias** [comment]
FYI, when you click on URL it also copies it to clipboard. You can click on the area on the top of the first browser if you don't want that to happen.

I added a beta-quality setting to allow exiting app when you unfocus the window.
Just open the new version, refresh the list of browsers and then edit the config file and change `quit_on_lost_focus` to `true`.

There are some bugs though: if you open the menu in the Browsers itself (or the About dialog) it will also exit. Will deal with that in future.

**Comment by codemedic** [comment]
@liias Thanks for adding this long-awaited feature. It seems it works only if I click on the popup and click away. At least in Linux + KDE, the window does not get focus and perhaps that is the reason. You might have to request focus (if that is a thing). It could also be the reason why the number shortcuts never worked for me (if that is how they are supposed to work).

**Comment by liias** [comment]
@codemedic thanks for feedback, I'll add it to my todo list, but I'm probably not getting to that very soon
