### ISSUE TITLE
Browsers UI double-displays if Safari is not already running when a link is clicked

### ISSUE THREAD

**Issue by jonnyborbs** [Browsers-software/browsers#79]
**Describe the bug**
When the Safari browser specifically (this was not observed with other browsers) is not already running, and a link is clicked in another application (Slack, for example, though it does not matter) and Safari is selected in the Browsers pop-up, Browsers will close, Safari will launch, the URL will open, but the Browsers UI opens a second time.

This only happens if the Safari browser is not already running. If it's open and able to immediately receive the request to open a site, there is no issue. But if the application needs to be launched first, there's some kind of a bounce happening

**System:**
 - OS: macOS Ventura 13.5
 - Browsers Version: 0.4.0

**Comment by liias** [comment]
Thank you for the bug report. I can confirm I can reproduce this issue.

**Comment by liias** [comment]
Shoulf be "fixed" in 0.4.1.

It's a really weird bug from Safari actually. If you set any browser (other than Safari) as your default browser. And launch url with Safari, then Safari will also launch the default browser.

I did a workaround where Browsers checks if it was started by Safari it will just exit. Can't do better than that for now.
