### ISSUE TITLE
Window appearing beneath Snap application

### ISSUE THREAD

**Issue by tommoyer** [Browsers-software/browsers#87]
**Describe the bug**
When I click a link with Browsers set as the default application, it appears but beneath the window every time. I tried three different applications (Thunderbird, Obsidian, and Gnome Terminal). This is using the X session for Gnome, not Wayland. I tested this under the default Wayland session with Gnome and it works there as expected.

**System:**
 - OS: [e.g. Ubuntu 23.10 with Gnome]
 - Browsers Version [e.g. 0.22.1] `⋮` -> About

**Comment by liias** [comment]
Hi @tommoyer!
Just to be clear (specially as I'm not native English speaker) - by beneath, you mean behind?
Second - do you really use Ubuntu 23.10 or that's there from the template bug report?

**Comment by tommoyer** [comment]
Yes, beneath meaning behind other windows. This only happens on the Xorg session.

I was testing it on both 23.04 and 23.10, just to see if it was something in the way Ubuntu configured Xorg but the behavior is consistent. As I indicated, the default Wayland session for Gnome does not show this behavior which leads me to think it is something with Xorg.

**Comment by liias** [comment]
Hmm. I tried 23.04 (but had to install arm64 server and then install desktop into it, so it may have different configuration) and it works for me in X.

Only app where it didn't work was if I ran the browsers command directly from terminal, then it appears behind the terminal,
but that happens with every app if launched from terminal.
Just to be sure, could you try latest nightly from https://nightly.link/Browsers-software/browsers/workflows/ci/main/browsers-linux-artifacts.zip

**Comment by tommoyer** [comment]
I just tested this with the nightly link in the above comment. It still does this but only for applications that are installed via snap. Any apt-based packages that I have installed are working just as expected. I'm not sure what the difference is, but I will keep looking.

**Comment by tommoyer** [comment]
I just submitted a pull request #97 that fixes this.

**Comment by liias** [comment]
Thank you again for figuring out the issue and the fix. The fix is now released in 0.4.2
