### ISSUE TITLE
Browsers not working on macOS

### ISSUE THREAD

**Issue by SteveMattan** [Browsers-software/browsers#9]
**Describe the bug**
Links in email do not open. Clicking then has no effect. No list of browsers is displayed.

**To Reproduce**
1. Click on a link.
2. Nothing happens.

**Expected behavior**
The app to work.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 12.6.2
 - Browsers.app 0.0.1

**Comment by liias** [comment]
Hi Steve, thank you for reporting the issue.

I need some more information to find the cause.

First, could you open a Terminal (Cmd+Space and search for "Terminal") and paste there the following line and press Enter:

```
RUST_BACKTRACE=full /Applications/Browsers.app/Contents/MacOS/Browsers 'https://www.google.com'
```

Then copy paste the output and post it here as a comment.


Second, do you know if you have Apple Silicon based mac or the Intel based mac? If needed, you can find it in the About this Mac menu in the top left under Chip like here:
![image](https://user-images.githubusercontent.com/2086180/214528534-5bf2408e-d7dc-4d05-b92f-73c7609fbca6.png)


Thanks!

**Comment by SteveMattan** [comment]
Madis,

Thank yo for the prompt reply. As requested:

Mac Studio Apple M1 Max.

~ ➤ RUST_BACKTRACE=full /Applications/Browsers.app/Contents/MacOS/Browsers 'https://www.google.com'                                                     7:14:04
2023-01-25T07:14:08.474619-05:00  INFO browsers: Starting Browsers
2023-01-25T07:14:08.474665-05:00  INFO browsers: Logging to /Users/stevemattan/Library/Logs/software.Browsers/browsers.log
2023-01-25T07:14:08.480254-05:00  INFO browsers::utils: Config: /Users/stevemattan/Library/Application Support/software.Browsers/config.json
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/ui.rs:53:42
stack backtrace:
   0:        0x1026d81ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he84d5e26d26c914d
   1:        0x10260f394 - core::fmt::write::h07c7e4739f78f3b0
   2:        0x1026b5a1c - std::io::Write::write_fmt::h4a3c5f094ffc65e8
   3:        0x1026db784 - std::sys_common::backtrace::print::h6fc2cc8be2392a8e
   4:        0x1026db3e4 - std::panicking::default_hook::{{closure}}::h3bb44ba6ff437e23
   5:        0x1026dc2b8 - std::panicking::rust_panic_with_hook::h9b8acc949e1fb807
   6:        0x1026dbe1c - std::panicking::begin_panic_handler::{{closure}}::hfc38b2cc56e3623c
   7:        0x1026dbdb0 - std::sys_common::backtrace::__rust_end_short_backtrace::hbafd151207fc448f
   8:        0x1026dbd8c - _rust_begin_unwind
   9:        0x1026fd100 - core::panicking::panic_fmt::h8c7f3d540a75578f
  10:        0x1026fd1a0 - core::panicking::panic::h2505ca165b8854d6
  11:        0x1025e679c - browsers::ui::UI::real_to_ui_browsers::h2e34b6bbd09f6ae7
  12:        0x1025a2e94 - browsers::basically_main::h920febe78a4fccdc
  13:        0x1025ff400 - browsers::main::h39fef18b4555ca41
  14:        0x102603b68 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7f8e7c3316bd894f
  15:        0x1025fdbac - _main

Hope this helps.

SteveM

**Comment by liias** [comment]
Thanks, that's very useful. Are you sure you use the latest version? Could you try re-installing from https://github.com/Browsers-software/browsers/releases/download/0.1.0-rc25/Browsers.dmg

**Comment by SteveMattan** [comment]
Well, based on the version number in the Get Info panel, yes. But I went ahead and reinstalled as per the link provided and it is now working. Thanks.

I use Unite (https://www.bzgapps.com/unite) to make single site apps. And all of these show up as options in the Browsers pallet. Is there a way to limit which browsers as shown in the Browsers pallet?

Thanks again,

SteveM

**Comment by liias** [comment]
Awesome!

I've been a bit lazy on versioning and just keep calling them all 1.0 Release Candidate so far.

Yeah, Hide should do the trick.
