### ISSUE TITLE
Donating to Browsers

### ISSUE THREAD

**Issue by vhtkrk** [Browsers-software/browsers#93]
Is there a way to give you money for creating such an awesome piece of software?

Google's enshittification of Chrome reached unbearable levels for me, finally pushing for a switch to Firefox. I need to use different profiles for work and personal stuff, and having all links open in one profile was driving me properly mad - almost had to switch back until I found your brilliant utility. And this is just perfect: cross platform, easy install, no further setup needed, and way better UX than any jank I had thought up as a solution to my problem. Thank you!

**Comment by liias** [comment]
Hi Joeli, sorry for never replying - I wasn't sure if I want to accept donations.

First of all, I'm happy you got a good experience!

I do have some donation accounts setup, but I also realize I probably don't want to feel the obligation of "people paid for it" and still keep it as a fun sideproject. But maybe one day.
