### ISSUE TITLE
Browsers seems to cause Arc to crash

### ISSUE THREAD

**Issue by jonnyborbs** [Browsers-software/browsers#94]
**Describe the bug**
When sending URLs to the Arc browser via Browsers, the browser crashes. It appears to be something to do with the way Arc sends the profile variable.

I've got it configured as follows (retrieving the Profile ID from the `config.json` after a manual reordering in the UI

```   
 {
      "source_app": null,
      "url_pattern": "*://*.mysite.url/**",
      "profile": "/Applications/Arc.app/Contents/MacOS/Arc#Profile 1",
      "incognito": false
    },
```

Opening links that match this pattern has the expected behavior of automatically routing the request to Arc, but then Arc immediately "has quit unexpectedly"

I tried disabling the "Little Arc" functionality that opens external URLs as a pop-over window, thinking that might be the cause. It didn't help.

**System:**
 - OS: MacOS 13.5.2, Arc 1.7.0, M2 silicon
 - Browsers Version 0.4.1

**Comment by liias** [comment]
Hey, @jonnyborbs, thanks for reporting this issue.

It looks like a problem in Arc indeed, as there is also other software causing segmentation fault in Arc when specifying `--profile-directory` argument. It looks like I need to disable support for profiles in Arc (at least on macOS) until this is resolved.

Feel free to contact Arc developers, but I doubt they care about this feature too much, but who knows.

**Comment by jonnyborbs** [comment]
Hi there, sorry to revisit this issue but I was wondering if there'd been any progress on disabling profiles or advice on how I can make Arc accept a URL from Browsers? I tried removing the `#Default` profile parameter and it didn't help. I'm on the latest version of both Arc and Browsers as of writing this note, and it still crashes when I try to open a link.

**Comment by liias** [comment]
> Hi there, sorry to revisit this issue but I was wondering if there'd been any progress on disabling profiles or advice on how I can make Arc accept a URL from Browsers? I tried removing the `#Default` profile parameter and it didn't help. I'm on the latest version of both Arc and Browsers as of writing this note, and it still crashes when I try to open a link.

Hey. Quickest workaround would be changing the [repository/application-repository.toml](https://github.com/Browsers-software/browsers/blob/main/resources/repository/application-repository.toml) and removing the first browser.

You can edit this file in `/Applications/Browsers.app/Contents/Resources/repository/application-repository.toml`. I will also remove it from release once I get some time.

```
[[apps]]
id = "company.thebrowser.Browser"
config_dir_relative = "Arc/User Data"
kind = "CHROMIUM"
os = "MAC"
```

Then it will show up without profile.

FYI I saw some chatter in https://www.reddit.com/r/ArcBrowser/comments/19bl4gy/support_choosing_profile_via_commandline_flag/ about it as well

**Comment by jonnyborbs** [comment]
Thanks, that worked well for Browsers. Now I'm trying to figure out how to update a few other apps that pass URLs to the browser in the same way. I sure wish Arc would do this in a standard format, even just running "../Arc $url" fails with the same crash on a command line. Not sure why they feel like it needs to be some complicated thing.

**Comment by liias** [comment]
In Browsers version 0.5.2 Arc profile support has been removed. I will close this issue until there's any updates from Arc side.
