### ISSUE TITLE
Enabling quit_on_lost_focus makes the "About" dialog not functional 😄 

### ISSUE THREAD

**Issue by jonnyborbs** [Browsers-software/browsers#95]
**Describe the bug**
When you have `quit_on_lost_focus` enabled in the config.json (LOVE this option BTW, thanks for adding it!), the "about" window can't be displayed, since it's a new modal and the Browsers main window loses focus and quits, taking the About dialog with it

**System:**
 - OS: MacOS 13.5.2, Arc 1.7.0, M2 silicon
 - Browsers Version 0.4.1

**Comment by liias** [comment]
Should be be better in 0.4.3 now. Only fixed for macOS, Windows and linux are more tricky to handle unfortunately.
